import { Button } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import SmartphoneIcon from '@mui/icons-material/Smartphone';
import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/Header';
import styles from '../styles/Home.module.css';
import Table from '../components/Table';
import api from '../lib/api';
import Link from 'next/link';

export async function getServerSideProps() {
    const data = await api.get('/phone').then((res) => res.data);
    return {
        props: { data },
    };
}

export default function Home(props) {
    const phones = props.data;

    return (
        <div className={styles.container}>
            <Head>
                <title>Melhor Celular</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={styles.main}>
                <div className={styles.products}>
                    <div className={styles.products_header}>
                        <h1>Produtos</h1>
                        <div>
                            <Button
                                variant="contained"
                                href="/add"
                                sx={{ backgroundColor: '#DAE3ED' }}
                            >
                                <AddIcon />
                                <SmartphoneIcon sx={{ marginRight: '3px' }} />
                                Adicionar
                            </Button>
                        </div>
                    </div>
                    <div>
                        <Table products={phones} />
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}
